apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: claim-postgres
  namespace: voting
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: manual